database:
  host: db.internal.company.com
  username: admin
  password: SuperSecret123!
  
aws:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  
api_keys:
  stripe: sk_live_1234567890abcdefghijklmnop
  sendgrid: SG.1234567890abcdefghijklmnopqrstuvwxyz